### ISSUE TITLE
Consider publishing your theme

### ISSUE THREAD

**Issue by twitu** [arzg/website#3]
I came across your blog while reading the making a language series. I find it to be an excellent combination of minimalism and readability. Consider sharing or publishing your theme, I'll surely use it.

**Comment by lunacookies** [comment]
Thank you for the compliment! I’m hesitant to separate out the `layouts` and `assets` folders into a theme because my website has a few peculiarities that mean it cannot really stand by itself. For example, code blocks that are meant to use a monospaced font have the language `-`, which is hacky and specific to the font I use and the content I write. Additionally, the fonts on the website are from [Adobe Fonts](https://fonts.adobe.com), which is a paid service.

If you want to use the website’s theme then go right ahead; just make sure to remove the SCSS related to the `-` language and Adobe Fonts (`assets/scss/fonts.scss`).

**Comment by twitu** [comment]
Oh got it. And it did occur to me that the fonts might be paid because they looked unique. Thanks again for the beautiful theme, I'll see if I can port parts of it.
